12th jan 2018:
---------------
Succeded in rectifying file not found error by importing 'BASE_DIR' parameter from settings module
and using os.path.join(BASE_DIR, 'key.py') to obtain the file path & using open() on the file path.
Found a hint that certain keys can be stored as environment var's in wsgi.py file. But didn't try out

Now the server started working at 'http://matrix89.pythonanywhere.com' ; But some other error's popped up
trying to post the messages as indicated below;

OSError: Tunnel connection failed: 403 Forbidden
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='matrix.org', port=8448): Max retries exceeded

Seems that there is something called "whitelist" of websites whose API's can be accessed by free beginner
account user's. I use a beginner account. For paid user's there is unrestricted access to all site API'S.
Here is link to whitelist. https://www.pythonanywhere.com/whitelist/

From my local server, I have tried sending few messages to the two test rooms, as mentioned in assignment
whoose link is given below.
test_room_1: https://riot.im/app/#/room/!whKbuarNiMcNeMMlVg:matrix.org
test_room_2: https://riot.im/app/#/room/!iCoOVDrUqeATFFdwyZ:matrix.org

All the messages send by "Dhanraj" are the ones tested by me from local server "http://localhost.com/8000"

11th jan 2108:
--------------

Simple python program to send message to 2 rooms:('test.py' file )
_______________________________________________

import requests, json

def key_obtain(file_name):
    key_obj = open(file_name,'r')
    key = key_obj.read().rstrip()
    key_obj.close()
    return key

def post_message(msg,r_id_1,r_id_2,f_name):
    acc = key_obtain(f_name)
    d = {"msgtype":"m.text","body":msg}
    url = "https://matrix.org:8448/_matrix/client/r0/rooms/%21{0}/send/m.room.message?access_token={1}".format(r_id_1, acc)
    r = requests.post(url, data = json.dumps(d), verify = False)
    url = "https://matrix.org:8448/_matrix/client/r0/rooms/%21{0}/send/m.room.message?access_token={1}".format(r_id_2, acc)
    q = requests.post(url, data = json.dumps(d), verify = False)

room_id_1 = "whKbuarNiMcNeMMlVg:matrix.org" #my test_room_2 internal id
room_id_2 = "iCoOVDrUqeATFFdwyZ:matrix.org" #my test_room_1 internal id
file_name = 'key.txt'                       #whatever is the access_key_file name; sould be in the same directory;
msg_to_post = "Good Morning"		    #a string

post_message(msg_to_post,room_id_1,room_id_2,file_name)
#######################################################

To store the access token in a file and only access it during the server startup:
_________________________________________________________________________________

Created a file called startup.py in project folder ('BASE_DIR/riot_chat/startup.py'). defined a function called run(name arbitrary) which returns the access token from a mentioned file ('key.py' in BASE_DIR) and it's stored for once and ever until server is restarted. This is done to avoid opening and closing the file, each time a message is to be posted. The variable 'acc_token' from wsgi file is imported to views and used thereafter.

To avoid SSL certificate warnings :
___________________________________

Tried using "requests.packages.urllib3.disable_warnings()" , after importing requests module

We can avoid using "verify = False" while accesing matrix.org api's.
This problem existed with using matrix-synapse local server

Hosting in pythonanywhere.com:
______________________________
Tried hosting in local server .
App works fine

Tried to host in pythonanywhere.com with my account.
But failed due to "filenotfound error" in pythonanywhere server. File containing the access key not found error; arising from function in 'startup.py' file

tried appending file's location to sys.path:

  path2 = os.path.dirname(os.path.expanduser(os.path.abspath(__file__)))
  if path2 not in sys.path:
        sys.path.append('path2')


But still the same error..

10th jan 2018:
--------------
error running synapse server "port 8448 already in use"
used "fuser -k 8448/tcp" to get around this problem. Did "synctl start" to start synapse server again.

Today tried to use api's directly from matrix.org rather than local server.

There are 2 types of user to matrix a) user b) guest

register "guest" user to matrix.org server:(works fine)
____________________________________
>>> d = {"username":"Catherine3982","password":"cathy123","bind_email":False}
>>> url = "https://matrix.org:8448/_matrix/client/r0/register?kind=guest"
>>> r = requests.post(url,data = json.dumps(d), verify = False)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
>>> r
<Response [200]>
>>> r.content
b'{"access_token":"MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI1Y2lkIHVzZXJfaWQgPSBANTI0MTIxOm1hdHJpeC5vcmcKMDAxNmNpZCB0eXBlID0gYWNjZXNzCjAwMjFjaWQgbm9uY2UgPSAjb0omOFBOOlM6Q2JnLnphCjAwMTVjaWQgZ3Vlc3QgPSB0cnVlCjAwMmZzaWduYXR1cmUgeCF4iLi5bZz0iLY7EOVTKrwc32W12V8JaHX6WjuTKDIK",
"home_server":"matrix.org","user_id":"@524121:matrix.org","device_id":"guest_device"}'

login "guest" user to matrix.org: (got error's)
_______________________________
Get's error's "Invalid password" while trying to login recently created guest account

d = {"user":"@524121:matrix.org","password":"cathy123","type":"m.login.password"}
url = "https://matrix.org:8448/_matrix/client/r0/login"
r = request.post(url,data = json.dumps(d),verify = False)
>>>r.content
b'{"errcode":"M_FORBIDDEN","error":"Invalid password"}'

tried "Catherine3982","@Catherine3982:matrix.org", as value to "user" key; but same error

register user to matrix.org server: (didn't try out after first stage. felt it's unnecessary)
_____________________________________
Its a multistaged interactive process called flows
Each flows may have different stages
status_code 401 is returned by server, until registration is successfully completed with status_code = 200
"session" key remains constant throughout the stages. it must be returned within "auth" key during interactions. "auth" key also contains "type" & another key corresponding to stage in which the process is in. When a stage is completed the server returns a "complete" key containing stages completed.

But not necessary for this project i feel..

login my already registered account at riot.im:(works fine)
______________________________________________

>>> d = {"user":"dhanraj","password":"its hidden","type":"m.login.password"}
>>> url = "https://matrix.org:8448/_matrix/client/r0/login"
>>> r = requests.post(url,data = json.dumps(d), verify = False)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
>>> r
<Response [200]>
>>> r.content
b'{"access_token":"MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI2Y2lkIHVzZXJfaWQgPSBAZGhhbnJhajptYXRyaXgub3JnCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0gVnQ9YkpuclQsLix2OXZPeAowMDJmc2lnbmF0dXJlIAxri4cRqvOiGGkvWBKNA_rs7YpBxpzK29fktFaY3d8-Cg",
"home_server":"matrix.org","user_id":"@dhanraj:matrix.org","device_id":"WAXINUFSZZ"}'

logging in my already registered account works. But the guest user account (created today) login doesn't work

messaging to a created room:(works fine)
____________________________
access_token used is the one obtained during logging in.
Using curl works...

curl -XPOST -k -d '{"msgtype":"m.text", "body":"hello"}' "https://matrix.org:8448/_matrix/client/r0/rooms/%21whKbuarNiMcNeMMlVg:matrix.org/send/m.room.message?access_token=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI2Y2lkIHVzZXJfaWQgPSBAZGhhbnJhajptYXRyaXgub3JnCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0gVnQ9YkpuclQsLix2OXZPeAowMDJmc2lnbmF0dXJlIAxri4cRqvOiGGkvWBKNA_rs7YpBxpzK29fktFaY3d8-Cg"
{
    "event_id": "$15156022131059360Pliup:matrix.org"
}

Using requests module of python.........

>>>data_to_post = {"msgtype":"m.text","body":"Helloooo!!!"}
>>>r_id = "whKbuarNiMcNeMMlVg:matrix.org"
>>>acc = "MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI2Y2lkIHVzZXJfaWQgPSBAZGhhbnJhajptYXRyaXgub3JnCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0gVnQ9YkpuclQsLix2OXZPeAowMDJmc2lnbmF0dXJlIAxri4cRqvOiGGkvWBKNA_rs7YpBxpzK29fktFaY3d8-Cg"
>>> url = "https://matrix.org:8448/_matrix/client/r0/rooms/%21{0}/send/m.room.message?access_token={1}".format(r_id, acc)
>>>r = requests.post(url, data = json.dumps(data_to_post), verify = False)
>>>r.content
b'{"event_id":"$15156030601074833cfSlS:matrix.org"}'


9th jan 2018:
-------------

REGISTER:
________
registered a new user in local server using curl command

''' curl -XPOST -d '{"username":"example", "password":"wordpass", "auth": {"type":"m.login.dummy"}}' "https://localhost:8448/_matrix/client/r0/register" '''
error with ssl certficate
entered the same above command using "-k" option of curl to get it done.

tried to do the same with python's requests module.
set 'verify = False' to avoid ssl certificate issue.

d = {"username":"dhanesh","password":"XXXXXXX", "auth":{"type":"m.login.dummy"}}
url = "https://localhost:8448/_matrix/client/r0/register"
headers = {'content-type':'application/json'}
r = requests.post(url,data = json.dumps(d),headers = headers, verify = False)

r.content
b'{"access_token":"MDAxOGxvY2F0aW9uIGRoYW5fbG9jYWwKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI2Y2lkIHVzZXJfaWQgPSBAZGhhbmVzaDpkaGFuX2xvY2FsCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0gNUBjMjFuYUVoSCNWQ1ArKwowMDJmc2lnbmF0dXJlIGeHMXPC1TT69XHvpP3Tnoa-pe7DMkkONJ6DRdh7EjxsCg","home_server":"dhan_local","user_id":"@dhanesh:dhan_local","device_id":"SVAHJLNZDU"}'

Following below also works
d = {"username":"David","password":"XXXXXXXX", "auth":{"type":"m.login.dummy"}}
r = requests.post(url,data = json.dumps(d),verify = False)

r.content.decode()
'{"access_token":"MDAxOGxvY2F0aW9uIGRoYW5fbG9jYWwKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI0Y2lkIHVzZXJfaWQgPSBAZGF2aWQ6ZGhhbl9sb2NhbAowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25jZSA9IDUyKmNZZG0wRkppYWFRYi0KMDAyZnNpZ25hdHVyZSDbiTgWDHLhxnbAx97LpLeDHl3wR5ErIMMPe4OZoWYFfwo","home_server":"dhan_local","user_id":"@david:dhan_local","device_id":"HGUHQFJKKD"}'

LOGIN:
______
How to log in a existing user
d = {"user":"David","password":"XXXXXX", "type":"m.login.password"}
l = requests.post(url, data = json.dumps(d),verify = False)
l.content
b'{"access_token":"MDAxOGxvY2F0aW9uIGRoYW5fbG9jYWwKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI0Y2lkIHVzZXJfaWQgPSBAZGF2aWQ6ZGhhbl9sb2NhbAowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25jZSA9IDFHdU1ScjBJMV5mZ0BjZUMKMDAyZnNpZ25hdHVyZSCaT3CQagq6bDYLANtf54vc2ym3wnwVFkafIt25vnnlHgo","home_server":"dhan_local","user_id":"@david:dhan_local","device_id":"CJWSGOEJWS"}'

ROOM CREATION:
_____________
Creating a room in local server

acc_token = "MDAxOGxvY2F0aW9uIGRoYW5fbG9jYWwKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI0Y2lkIHVzZXJfaWQgPSBAZGF2aWQ6ZGhhbl9sb2NhbAowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25jZSA9IDFHdU1ScjBJMV5mZ0BjZUMKMDAyZnNpZ25hdHVyZSCaT3CQagq6bDYLANtf54vc2ym3wnwVFkafIt25vnnlHgo"
url = "https://localhost:8448/_matrix/client/r0/createRoom?access_token=%s" % acc_token
q = requests.post(url,data = json.dumps(d),verify = False)
q.content
b'{"room_alias":"#test_room_1:dhan_local","room_id":"!uYIlniPHepLWKSnpXT:dhan_local"}'

GET STATUS OF ROOMS:
___________________
r = requests.get("https://localhost:8448/_matrix/client/r0/sync?access_token=MDAxOGxvY2F0aW9uIGRoYW5fbG9jYWwKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI0Y2lkIHVzZXJfaWQgPSBAZGF2aWQ6ZGhhbl9sb2NhbAowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25jZSA9IDFHdU1ScjBJMV5mZ0BjZUMKMDAyZnNpZ25hdHVyZSCaT3CQagq6bDYLANtf54vc2ym3wnwVFkafIt25vnnlHgo", verify = False)

>>>for i in json.loads(r.content.decode()):
...     print(i)
...
rooms
device_lists
groups
account_data
to_device
presence
device_one_time_keys_count
next_batch

SENDING MESSAGE TO ROOM:
_______________________
Tried to use previously created user named "dhanesh" to message to 'test_room_1'. got an ERROR

d = {"msgtype":"m.text","body":"hellooo"}

url = "https://localhost:8448/_matrix/client/r0/rooms/%21!uYIlniPHepLWKSnpXT:localhost/send/m.room.message?access_token=MDAxOGxvY2F0aW9uIGRoYW5fbG9jYWwKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI2Y2lkIHVzZXJfaWQgPSBAZGhhbmVzaDpkaGFuX2xvY2FsCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0gNUBjMjFuYUVoSCNWQ1ArKwowMDJmc2lnbmF0dXJlIGeHMXPC1TT69XHvpP3Tnoa-pe7DMkkONJ6DRdh7EjxsCg"

a = requests.post(url, data = json.dumps(d), verify = False)

a.content
b'{"errcode":"M_UNKNOWN","error":"Room \'!!uYIlniPHepLWKSnpXT:localhost\' does not exist"}'


8th Jan 2018:
-------------

Installed matrix-synapse which would be nedded to test things locally. Installed correctly. Configuring synapse got lot of import error. solved some of them. But few other error's is about missing packages.

Error1:
ImportError: No module named 'Queue'

>>> pip3 install Queue
Could not find a version that satisfies the requirement Queue (from versions: )
No matching distribution found for Queue

vi lib/python3.5/site-packages/synapse/storage/event_federation.py
entered "from multiprocessing import Queue"
and tried configuring again.
But still the same error
There is no other file named Queue.py in the directory containing the event_federeation.py file
rectified that mistake by renaming Queue with queue

Similar errors related to packages compatability between python2 and python3
Uninstalled the done installation and trying to install based on python2.7

got the synapse server running


﻿6th Jan 2018:
-------------


a) Started with second assignment
b)created riot.im account and two test chat rooms. saved the access token of my account.
c)started going through the api's of matrix, which would be needed for the django project.
d)how to convert curl commands in api's to functions of requests module
